#!/usr/bin/env python3
"""Build a deterministic PIT fixture inside an isolated QA root.

The generated bytes are synthetic test evidence and are deliberately marked
``production_eligible=false``.  They exercise the real immutable membership,
dual-price ledger, runtime binding, cache, benchmark and database code paths;
they are never copied into the repository's production ``data/`` directory.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import math
import sqlite3
from pathlib import Path
import sys

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.api.auth import _hash_password  # noqa: E402
from backend.config import settings  # noqa: E402
from backend.data.cache import DataCache  # noqa: E402
from backend.data.pit_qa import (  # noqa: E402
    QA_ATTESTATION_SCHEMA,
    QA_MARKER_SCHEMA,
    qa_attestation_sha256,
)
from backend.data.point_in_time_master import (  # noqa: E402
    IMPORT_SCHEMA_VERSION as PIT_IMPORT_SCHEMA,
    PointInTimeMasterStore,
    _authorize_governed_import,
    _digest as pit_digest,
)
from backend.data.point_in_time_universe import (  # noqa: E402
    resolve_point_in_time_universe,
)
from backend.data.price_ledger import (  # noqa: E402
    IMPORT_SCHEMA_VERSION as PRICE_IMPORT_SCHEMA,
    PriceLedgerStore,
)
from backend.data.source_validation import (  # noqa: E402
    build_cache_source_provenance,
    build_daily_fetch_evidence,
)
from backend.main import _init_databases  # noqa: E402


CODES = tuple(f"{600001 + index:06d}" for index in range(300))
POOL_IDS = ("csi300", "csi500", "csi800", "csi1000")


def _require_isolated_configuration(root: Path) -> None:
    configured = Path(settings.PIT_QA_FIXTURE_ROOT).expanduser().resolve()
    if settings.ENVIRONMENT != "test" or configured != root:
        raise RuntimeError(
            "Run with ENVIRONMENT=test and PIT_QA_FIXTURE_ROOT equal to --root"
        )
    production_data = (PROJECT_ROOT / "data").resolve()
    try:
        root.relative_to(production_data)
    except ValueError:
        pass
    else:
        raise RuntimeError("QA fixture root must not be inside production data/")
    if any(root.iterdir()):
        raise RuntimeError("QA fixture root must be empty")


def _market_frame(dates: pd.DatetimeIndex) -> pd.DataFrame:
    columns = pd.MultiIndex.from_product(
        [CODES, ("open", "high", "low", "close", "volume")],
        names=("code", "field"),
    )
    frame = pd.DataFrame(index=dates, columns=columns, dtype="float64")
    for rank, code in enumerate(CODES):
        closes = [
            9.0
            + rank * 0.006
            + day * (0.0008 + (rank % 7) * 0.00005)
            + 0.35 * math.sin(day / (5.0 + rank % 9) + rank / 17.0)
            for day in range(len(dates))
        ]
        close = pd.Series(closes, index=dates, dtype="float64")
        open_price = close * (1.0 + 0.002 * math.sin(rank + 0.3))
        frame[(code, "open")] = open_price
        frame[(code, "high")] = pd.concat([close, open_price], axis=1).max(axis=1) * 1.01
        frame[(code, "low")] = pd.concat([close, open_price], axis=1).min(axis=1) * 0.99
        frame[(code, "close")] = close
        frame[(code, "volume")] = 1_000_000.0 + rank * 100 + pd.Series(
            range(len(dates)), index=dates, dtype="float64"
        )
    frame.index.name = "date"
    return frame


def _activate_membership(store: PointInTimeMasterStore, start: str, end: str) -> None:
    package_id = "pitpkg_" + "a" * 32
    package_sha256 = hashlib.sha256(b"isolated-pit-qa-package").hexdigest()
    receipts: list[dict[str, str]] = []
    for index, scope_id in enumerate(POOL_IDS):
        document = {
            "schema_version": PIT_IMPORT_SCHEMA,
            "domain": "index_membership",
            "scope_id": scope_id,
            "evidence_kind": "effective_dated_history",
            "coverage_from": start,
            "coverage_to": end,
            "source": {
                "provider": "csindex_official",
                "dataset": "isolated-non-production-pit-qa-membership",
                "version": "qa-v1",
                "evidence_level": "index_provider_authoritative",
                "retrieved_at": "2025-01-02T00:00:00Z",
                "content_sha256": hashlib.sha256(
                    f"qa-membership-{scope_id}-{index}".encode()
                ).hexdigest(),
            },
            "records": [
                {
                    "security_code": code,
                    "effective_from": start,
                    "effective_to": end,
                    "member_name": f"QA-{code}",
                }
                for code in CODES
            ],
        }
        imported = store.import_batch(
            **document,
            imported_by_user_id=1,
            _governed_authorization=_authorize_governed_import(
                package_id=package_id,
                package_sha256=package_sha256,
                document_sha256=pit_digest(document),
            ),
        )
        receipts.append(
            {
                "scope_id": scope_id,
                "batch_id": imported["batch_id"],
                "batch_digest": imported["batch_digest"],
            }
        )
    store.activate_governed_csi_package(
        package_id=package_id,
        package_sha256=package_sha256,
        receipts=receipts,
    )


def _price_rows(frame: pd.DataFrame) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for day in frame.index:
        date_text = day.strftime("%Y-%m-%d")
        for code in CODES:
            rows.append(
                {
                    "security_code": code,
                    "date": date_text,
                    "open": float(frame.at[day, (code, "open")]),
                    "high": float(frame.at[day, (code, "high")]),
                    "low": float(frame.at[day, (code, "low")]),
                    "close": float(frame.at[day, (code, "close")]),
                    "volume": float(frame.at[day, (code, "volume")]),
                }
            )
    return rows


async def _build(root: Path) -> dict[str, object]:
    await _init_databases()
    with sqlite3.connect(settings.abs_path(settings.USERS_DB)) as connection:
        connection.execute(
            """
            INSERT INTO users (
                username, password_hash, display_name, is_admin, is_active
            ) VALUES (?, ?, ?, 1, 1)
            """,
            ("qa_admin", _hash_password("qa-admin-123"), "PIT QA Admin"),
        )
        connection.commit()

    dates = pd.bdate_range("2022-11-28", "2024-03-29", name="date")
    start = dates[0].strftime("%Y-%m-%d")
    end = dates[-1].strftime("%Y-%m-%d")
    frame = _market_frame(dates)
    database = settings.abs_path(settings.EXPERIMENT_DB)
    pit_store = PointInTimeMasterStore(database)
    _activate_membership(pit_store, start, "2026-12-31")

    source_template = {
        "provider": "isolated-pit-qa",
        "dataset": "deterministic-dual-price-fixture",
        "version": "qa-v1",
        "retrieved_at": "2025-01-02T00:00:00Z",
        "evidence_level": "declared",
    }
    rows = _price_rows(frame)
    ledger = PriceLedgerStore(database)
    imported = ledger.import_batch(
        schema_version=PRICE_IMPORT_SCHEMA,
        scope_id="csi300",
        coverage_from=start,
        coverage_to=end,
        raw_source={
            **source_template,
            "adjustment": "raw",
            "content_sha256": hashlib.sha256(b"qa-raw-prices").hexdigest(),
        },
        research_source={
            **source_template,
            "adjustment": "hfq",
            "content_sha256": hashlib.sha256(b"qa-hfq-prices").hexdigest(),
        },
        corporate_action_source=None,
        raw_prices=rows,
        research_prices=rows,
        corporate_actions=[],
        imported_by_user_id=1,
    )
    timeline = resolve_point_in_time_universe(
        pit_store,
        pool_id="csi300",
        trading_dates=dates,
        expected_count=300,
    )
    binding = ledger.bind_runtime_scope(
        scope_id="csi300",
        timeline_identity=timeline.identity(),
        trading_dates=timeline.dates,
        batch_ids=[imported["batch_id"]],
        status_source={
            **source_template,
            "dataset": "deterministic-session-status-fixture",
            "adjustment": "trading_status",
            "content_sha256": hashlib.sha256(b"qa-session-status").hexdigest(),
        },
        suspension_observations=[],
        bound_by_user_id=1,
    )

    fetch_evidence = build_daily_fetch_evidence(
        frame,
        requested_codes=CODES,
        start=start,
        end=end,
        provider="isolated-pit-qa",
        endpoint="fixture:deterministic/non-network",
        adjustment="hfq",
        evidence_level="declared",
        transformations=["qa_fixture_only", "no_network_access"],
    )
    cache = DataCache()
    await cache.save_pivot(
        "csi300",
        frame,
        source_provenance=build_cache_source_provenance(
            frame,
            [fetch_evidence],
        ),
    )
    benchmark = pd.Series(
        [3000.0 + index * 0.8 for index in range(len(dates))],
        index=dates,
        name="close",
        dtype="float64",
    )
    await cache.save_index("000300", benchmark)
    benchmark_path = root / "cache" / "indexes" / "000300.parquet"
    attestation: dict[str, object] = {
        "schema_version": QA_ATTESTATION_SCHEMA,
        "non_production": True,
        "production_eligible": False,
        "fixture_kind": "deterministic_isolated_pit_e2e",
        "pool_id": "csi300",
        "coverage_from": start,
        "coverage_to": end,
        "timeline_hash": timeline.timeline_hash,
        "binding_id": binding["binding_id"],
        "binding_digest": binding["binding_digest"],
        "benchmark_artifact": str(benchmark_path.relative_to(root)),
        "benchmark_artifact_sha256": hashlib.sha256(
            benchmark_path.read_bytes()
        ).hexdigest(),
        "network_accessed": False,
    }
    attestation["attestation_sha256"] = qa_attestation_sha256(attestation)
    Path(settings.PIT_QA_ATTESTATION).write_text(
        json.dumps(attestation, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return {
        "status": "prepared",
        "qa_root": str(root),
        "database": str(database),
        "code_count": len(CODES),
        "session_count": len(dates),
        "timeline_hash": timeline.timeline_hash,
        "binding_id": binding["binding_id"],
        "binding_digest": binding["binding_digest"],
        "production_eligible": False,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path)
    args = parser.parse_args()
    root = args.root.expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    _require_isolated_configuration(root)
    (root / ".pit-qa-only.json").write_text(
        json.dumps(
            {"schema_version": QA_MARKER_SCHEMA, "non_production": True},
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    print(json.dumps(asyncio.run(_build(root)), ensure_ascii=False))


if __name__ == "__main__":
    main()
